name: Scan Release Assets

permissions:
  contents: write # Needed to update the release notes with the VT link

on:
  release:
    types: [published]
  workflow_dispatch: # Allows you to click "Run workflow" manually in the Actions tab

jobs:
  virustotal:
    runs-on: ubuntu-latest
    steps:
      - name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          # Monitors both Windows and Mac installers
          files: |
            ./*.exe
            ./*.dmg
          # This adds the VT report link to your GitHub Release description
          update_release_body: true
